module Evergreen.Migrate.V7 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V5.Table
import Evergreen.V5.Types
import Evergreen.V7.Table
import Evergreen.V7.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V5.Types.FrontendModel -> ModelMigration Evergreen.V7.Types.FrontendModel Evergreen.V7.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V5.Types.BackendModel -> ModelMigration Evergreen.V7.Types.BackendModel Evergreen.V7.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V5.Types.FrontendMsg -> MsgMigration Evergreen.V7.Types.FrontendMsg Evergreen.V7.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V5.Types.ToBackend -> MsgMigration Evergreen.V7.Types.ToBackend Evergreen.V7.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V5.Types.BackendMsg -> MsgMigration Evergreen.V7.Types.BackendMsg Evergreen.V7.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V5.Types.ToFrontend -> MsgMigration Evergreen.V7.Types.ToFrontend Evergreen.V7.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V5.Types.BackendModel -> Evergreen.V7.Types.BackendModel
migrate_Types_BackendModel old =
    { gameCount = old.gameCount
    , pewsPewed = old.pewsPewed
    , trollbox = []
    }


migrate_Types_FrontendModel : Evergreen.V5.Types.FrontendModel -> Evergreen.V7.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , gameState = old.gameState |> migrate_Types_GameState
    , gameCount = old.gameCount
    , pewsPewed = old.pewsPewed
    , chatInput = ""
    , trollbox = []
    }


migrate_Table_Table : (a_old -> a_new) -> Evergreen.V5.Table.Table a_old -> Evergreen.V7.Table.Table a_new
migrate_Table_Table migrate_a old =
    case old of
        Evergreen.V5.Table.Table p0 p1 ->
            Evergreen.V7.Table.Table p0 (p1 |> Dict.map (\k -> migrate_a))


migrate_Types_BackendMsg : Evergreen.V5.Types.BackendMsg -> Evergreen.V7.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V5.Types.NoOpBackendMsg ->
            Evergreen.V7.Types.NoOpBackendMsg


migrate_Types_Body : Evergreen.V5.Types.Body -> Evergreen.V7.Types.Body
migrate_Types_Body old =
    { id = old.id
    , mass = old.mass
    , position = old.position |> migrate_Types_Vector2D
    , velocity = old.velocity |> migrate_Types_Vector2D
    , radius = old.radius
    , bodyType = old.bodyType |> migrate_Types_BodyType
    }


migrate_Types_BodyType : Evergreen.V5.Types.BodyType -> Evergreen.V7.Types.BodyType
migrate_Types_BodyType old =
    case old of
        Evergreen.V5.Types.Conceptual ->
            Evergreen.V7.Types.Conceptual

        Evergreen.V5.Types.Planet p0 ->
            Evergreen.V7.Types.Planet p0

        Evergreen.V5.Types.Ship p0 ->
            Evergreen.V7.Types.Ship
                { rotation = p0.rotation
                , rotationSpeed = p0.rotationSpeed
                , propulsion = p0.propulsion |> migrate_Types_PropulsionType
                , projectile = p0.projectile |> migrate_Types_ProjectileType
                , maxCrew = p0.maxCrew
                , crew = p0.crew
                }

        Evergreen.V5.Types.Projectile p0 ->
            Evergreen.V7.Types.Projectile (p0 |> migrate_Types_ProjectileType)


migrate_Types_Direction : Evergreen.V5.Types.Direction -> Evergreen.V7.Types.Direction
migrate_Types_Direction old =
    case old of
        Evergreen.V5.Types.Left ->
            Evergreen.V7.Types.Left

        Evergreen.V5.Types.Right ->
            Evergreen.V7.Types.Right


migrate_Types_FrontendMsg : Evergreen.V5.Types.FrontendMsg -> Evergreen.V7.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V5.Types.UrlClicked p0 ->
            Evergreen.V7.Types.UrlClicked p0

        Evergreen.V5.Types.UrlChanged p0 ->
            Evergreen.V7.Types.UrlChanged p0

        Evergreen.V5.Types.NoOpFrontendMsg ->
            Evergreen.V7.Types.NoOpFrontendMsg

        Evergreen.V5.Types.GameMsg p0 ->
            Evergreen.V7.Types.GameMsg (p0 |> migrate_Types_GameMsg)

        Evergreen.V5.Types.NewGame ->
            Evergreen.V7.Types.NewGame


migrate_Types_GameMsg : Evergreen.V5.Types.GameMsg -> Evergreen.V7.Types.GameMsg
migrate_Types_GameMsg old =
    case old of
        Evergreen.V5.Types.NoAction ->
            Evergreen.V7.Types.NoAction

        Evergreen.V5.Types.FrameTick p0 ->
            Evergreen.V7.Types.FrameTick p0

        Evergreen.V5.Types.FireProjectile p0 ->
            Evergreen.V7.Types.FireProjectile p0

        Evergreen.V5.Types.Rotate p0 p1 ->
            Evergreen.V7.Types.Rotate (p0 |> migrate_Types_Direction) p1

        Evergreen.V5.Types.Propel p0 ->
            Evergreen.V7.Types.Propel p0

        Evergreen.V5.Types.KeyPressed p0 ->
            Evergreen.V7.Types.KeyPressed p0

        Evergreen.V5.Types.KeyReleased p0 ->
            Evergreen.V7.Types.KeyReleased p0


migrate_Types_GameState : Evergreen.V5.Types.GameState -> Evergreen.V7.Types.GameState
migrate_Types_GameState old =
    { bodies = old.bodies |> migrate_Table_Table migrate_Types_Body
    , timeElapsed = old.timeElapsed
    , space = old.space |> migrate_Types_Space
    , entropyCount = old.entropyCount
    , depressedKeys = old.depressedKeys
    }


migrate_Types_ProjectileType : Evergreen.V5.Types.ProjectileType -> Evergreen.V7.Types.ProjectileType
migrate_Types_ProjectileType old =
    case old of
        Evergreen.V5.Types.Kenetic p0 ->
            Evergreen.V7.Types.Kenetic p0

        Evergreen.V5.Types.Photonic p0 ->
            Evergreen.V7.Types.Photonic p0


migrate_Types_PropulsionType : Evergreen.V5.Types.PropulsionType -> Evergreen.V7.Types.PropulsionType
migrate_Types_PropulsionType old =
    case old of
        Evergreen.V5.Types.Newtonian p0 ->
            Evergreen.V7.Types.Newtonian p0

        Evergreen.V5.Types.LittleGrayMenTech p0 ->
            Evergreen.V7.Types.LittleGrayMenTech p0


migrate_Types_Space : Evergreen.V5.Types.Space -> Evergreen.V7.Types.Space
migrate_Types_Space old =
    old


migrate_Types_ToBackend : Evergreen.V5.Types.ToBackend -> Evergreen.V7.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V5.Types.NoOpToBackend ->
            Evergreen.V7.Types.NoOpToBackend

        Evergreen.V5.Types.NewGameStarted ->
            Evergreen.V7.Types.NewGameStarted

        Evergreen.V5.Types.PewPewed ->
            Evergreen.V7.Types.PewPewed


migrate_Types_ToFrontend : Evergreen.V5.Types.ToFrontend -> Evergreen.V7.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V5.Types.NoOpToFrontend ->
            Evergreen.V7.Types.NoOpToFrontend

        Evergreen.V5.Types.GlobalUpdate p0 ->
            Evergreen.V7.Types.GlobalUpdate
                { gameCount = p0.gameCount
                , pewsPewed = p0.pewsPewed
                , trollbox = []
                }


migrate_Types_Vector2D : Evergreen.V5.Types.Vector2D -> Evergreen.V7.Types.Vector2D
migrate_Types_Vector2D old =
    old
